
export const rows = [
  {
    id: 1,
    name: "Ismail Bakhach",
    email: "nicktrig@gmail.com",
    age: 65,
    phone: "(444)555-6590",
    access: "Admin",
  },
  {
    id: 2,
    name: "Sara Ankoud",
    email: "miyop@verizon.net",
    age: 15,
    phone: "(206) 342-8631",
    access: "Admin",
  },
  {
    id: 3,
    name: "Tony Moukbel",
    email: "psichel@optonline.net",
    age: 44,
    phone: "(253) 644-2182",
    access: "Admin",
  },
  {
    id: 4,
    name: "Ali Dandashi",
    email: "speeves@mac.com",
    age: 27,
    phone: "(262) 162-1585",
    access: "Admin",
  },
  {
    id: 5,
    name: "Samira Hello",
    email: "rtanter@aol.com",
    age: 28,
    phone: "(717) 550-1675",
    access: "Manager",
  },
  {
    id: 6,
    name: "Rony Rizik",
    email: "wonderkid@comcast.net",
    age: 30,
    phone: "(212) 658-3916",
    access: "Manager",
  },
  {
    id: 7,
    name: "Ahmad Ridani",
    email: "mhanoh@me.com",
    age: 33,
    phone: "(209) 300-2557",
    access: "User",
  },
  {
    id: 8,
    name: "Abed Malass",
    email: "crobles@aol.com",
    age: 23,
    phone: "(234) 109-6666",
    access: "User",
  },
  {
    id: 9,
    name: "Midhat Alamdin",
    email: "wbarker@optonline.net",
    age: 25,
    phone: "(201) 874-8593",
    access: "User",
  },
];

