export const columns = [
  { field: "id", headerName: "Id", width: 33, flex: 1 },
  { field: "registrarId", headerName: "Registrar Id", flex: 1 },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  { field: "email", headerName: "Email", flex: 1 },
  {
    field: "age",
    headerName: "Age",
    flex: 1,
    type: "number",
    headerAlign: "left",
    align: "left",
    width: 44
  },
  { field: "phone", headerName: "Phone", flex: 1 },
  { field: "address", headerName: "Address", flex: 1 },
  { field: "city", headerName: "City", flex: 1 },
  { field: "zipCode", headerName: "ZipCode", flex: 1 },
];

export const rows = [
  {
    id: 1,
    name: "Ismail Bakhach",
    email: "nicktrig@gmail.com",
    age: 65,
    phone: "(444)555-6590",

    address: "539 Thea Way",
    city: "Savannah",
    zipCode: "29456",
    registrarId: 123512,
  },
  {
    id: 2,
    name: "Sara Ankoud",
    email: "miyop@verizon.net",
    age: 15,
    phone: "(206) 342-8631",

    address: "6069 Marianne Plaza",
    city: "East Houstonbury",
    zipCode: "10291",
    registrarId: 234765,
  },
  {
    id: 3,
    name: "Tony Moukbel",
    email: "psichel@optonline.net",
    age: 44,
    phone: "(253) 644-2182",

    address: "11853 Jerrod River",
    city: "Tokyo",
    zipCode: "12345",
    registrarId: 164845,
  },
  {
    id: 4,
    name: "Ali Dandashi",
    email: "speeves@mac.com",
    age: 27,
    phone: "(262) 162-1585",

    address: "17349 Lynch Center",
    city: "Houston",
    zipCode: "35236",
    registrarId: 675849,
  },
  {
    id: 5,
    name: "Samira Hello",
    email: "rtanter@aol.com",
    age: 28,
    phone: "(717) 550-1675",

    address: "73587 Linnea Way",
    city: "Manhaten",
    zipCode: "56789",
    registrarId: 928734,
  },
  {
    id: 6,
    name: "Rony Rizik",
    email: "wonderkid@comcast.net",
    age: 30,
    phone: "(212) 658-3916",

    address: "210 Treutel Prairie",
    city: "Bufordborough",
    zipCode: "65784",
    registrarId: 867463,
  },
  {
    id: 7,
    name: "Ahmad Ridani",
    email: "mhanoh@me.com",
    age: 33,
    phone: "(209) 300-2557",

    address: "21385 Gottlieb Spring",
    city: "New Georgianna",
    zipCode: "12378",
    registrarId: 867493,
  },
  {
    id: 8,
    name: "Abed Malass",
    email: "crobles@aol.com",
    age: 23,
    phone: "(234) 109-6666",

    address: "350 Grady Ville",
    city: "Darebury",
    zipCode: "75623",
    registrarId: 893190,
  },
  {
    id: 9,
    name: "Midhat Alamdin",
    email: "wbarker@optonline.net",
    age: 25,
    phone: "(201) 874-8593",

    address: "55996 Cormier Path",
    city: "Ginomouth",
    zipCode: "13472",
    registrarId: 987364,
  },
];
